In [3]:
import pandas as pd
import numpy as np

In [4]:
customers = pd.read_csv("../Raw Data/olist_customers_dataset.csv")
orders = pd.read_csv("../Raw Data/olist_orders_dataset.csv")
order_items = pd.read_csv("../Raw Data/olist_order_items_dataset.csv")
products = pd.read_csv("../Raw Data/olist_products_dataset.csv")
payments = pd.read_csv("../Raw Data/olist_order_payments_dataset.csv")
reviews = pd.read_csv("../Raw Data/olist_order_reviews_dataset.csv")
sellers = pd.read_csv("../Raw Data/olist_sellers_dataset.csv")
geolocation = pd.read_csv("../Raw Data/olist_geolocation_dataset.csv")
category_translation = pd.read_csv("../Raw Data/product_category_name_translation.csv")

In [5]:
customers.shape

(99441, 5)

In [6]:
print("Customers:", customers.shape)
print("Orders:", orders.shape)
print("Order Items:", order_items.shape)
print("Products:", products.shape)
print("Payments:", payments.shape)
print("Reviews:", reviews.shape)
print("Sellers:", sellers.shape)
print("Geolocation:", geolocation.shape)
print("Category:", category_translation.shape)

Customers: (99441, 5)
Orders: (99441, 8)
Order Items: (112650, 7)
Products: (32951, 9)
Payments: (103886, 5)
Reviews: (99224, 7)
Sellers: (3095, 4)
Geolocation: (1000163, 5)
Category: (71, 2)

In [7]:
customers_clean = customers.copy()

orders_clean = orders.copy()

order_items_clean = order_items.copy()

products_clean = products.copy()

payments_clean = payments.copy()

reviews_clean = reviews.copy()

sellers_clean = sellers.copy()

geolocation_clean = geolocation.copy()

category_translation_clean = category_translation.copy()

In [8]:
customers_clean.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [9]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [10]:
print(customers.shape)
print(customers_clean.shape)

(99441, 5)
(99441, 5)

In [11]:
customers is customers_clean

False

In [12]:
customers_clean.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [13]:
customers_clean["customer_id"].duplicated().sum()

np.int64(0)

In [14]:
customers_clean.duplicated().sum()

np.int64(0)

In [15]:
customers_clean.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [16]:
customers_clean["customer_city"] = (
    customers_clean["customer_city"]
    .str.lower()
    .str.strip()
)

In [17]:
customers_clean["customer_state"] = (
    customers_clean["customer_state"]
    .str.upper()
    .str.strip()
)

In [18]:
customers_clean["customer_city"].nunique()

4119

In [19]:
customers["customer_city"].nunique()

4119

In [20]:
customers_clean["customer_city"].head(10)

0                   franca
1    sao bernardo do campo
2                sao paulo
3          mogi das cruzes
4                 campinas
5           jaragua do sul
6                sao paulo
7                  timoteo
8                 curitiba
9           belo horizonte
Name: customer_city, dtype: object

In [21]:
print(customers_clean["customer_city"].head(10))

0                   franca
1    sao bernardo do campo
2                sao paulo
3          mogi das cruzes
4                 campinas
5           jaragua do sul
6                sao paulo
7                  timoteo
8                 curitiba
9           belo horizonte
Name: customer_city, dtype: object

In [22]:
customers_clean.shape

(99441, 5)

In [23]:
customers_clean = customers.copy()

In [24]:
customers_clean.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')

In [25]:
print("Hello")

Hello

In [26]:
customers_clean["customer_city"] = (
    customers_clean["customer_city"]
    .str.lower()
    .str.strip()
)


customers_clean["customer_state"] = (
    customers_clean["customer_state"]
    .str.upper()
    .str.strip()
)

In [27]:
customers_clean.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [28]:
customers_clean.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [29]:
customers_clean["customer_id"].duplicated().sum()

np.int64(0)

In [30]:
customers.equals(customers_clean)

True

In [31]:
customers is customers_clean

False

In [32]:
customers_clean["customer_city"] = (
    customers_clean["customer_city"]
    .str.lower()
    .str.strip()
)

In [33]:
customers_clean.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [34]:
customers_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [35]:
customers_clean["customer_city"].head(10)

0                   franca
1    sao bernardo do campo
2                sao paulo
3          mogi das cruzes
4                 campinas
5           jaragua do sul
6                sao paulo
7                  timoteo
8                 curitiba
9           belo horizonte
Name: customer_city, dtype: object

In [36]:
customers_clean["customer_state"].unique()

array(['SP', 'SC', 'MG', 'PR', 'RJ', 'RS', 'PA', 'GO', 'ES', 'BA', 'MA',
       'MS', 'CE', 'DF', 'RN', 'PE', 'MT', 'AM', 'AP', 'AL', 'RO', 'PB',
       'TO', 'PI', 'AC', 'SE', 'RR'], dtype=object)

In [37]:
customers_clean.to_csv(
    "../Cleaned Data/customers_clean.csv",
    index=False
)

In [9]:
import os

os.listdir("../Cleaned Data")

['customers_clean.csv', 'orders_clean.csv']

In [10]:
orders_clean = orders.copy()

NameError: name 'orders' is not defined

In [11]:
orders.head()

NameError: name 'orders' is not defined

In [12]:
orders_clean.shape

NameError: name 'orders_clean' is not defined

In [13]:
orders_clean.info()

NameError: name 'orders_clean' is not defined

In [47]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]


for col in date_columns:
    orders_clean[col] = pd.to_datetime(orders_clean[col])

ValueError: time data "24-07-2018 20:41" doesn't match format "%m-%d-%Y %H:%M", at position 1. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [48]:
orders_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [49]:
orders_clean.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [50]:
orders_clean[
    orders_clean["order_delivered_customer_date"].isnull()
]["order_status"].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [51]:
orders_clean["order_id"].duplicated().sum()

np.int64(0)

In [52]:
orders_clean["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [53]:
orders_clean["delivery_days"] = (
    orders_clean["order_delivered_customer_date"]
    - orders_clean["order_purchase_timestamp"]
).dt.days

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [54]:
orders_clean["delivery_days"].describe()

KeyError: 'delivery_days'

In [ ]:
orders_clean["approval_days"] = (
    orders_clean["order_approved_at"]
    - orders_clean["order_purchase_timestamp"]
).dt.days

In [55]:
orders_clean["approval_days"].describe()

KeyError: 'approval_days'

In [56]:
orders_clean["delay_days"] = (
    orders_clean["order_delivered_customer_date"]
    - orders_clean["order_estimated_delivery_date"]
).dt.days

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [57]:
orders_clean["delay_days"].describe()

KeyError: 'delay_days'

In [58]:
(orders_clean["delay_days"] > 0).sum()

KeyError: 'delay_days'

In [59]:
(orders_clean["delay_days"] < 0).sum()

KeyError: 'delay_days'

In [60]:
(orders_clean["delay_days"] == 0).sum()

KeyError: 'delay_days'

In [61]:
orders_clean.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,02-10-2017 10:56,02-10-2017 11:07,04-10-2017 19:55,10-10-2017 21:25,18-10-2017 00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,24-07-2018 20:41,26-07-2018 03:24,26-07-2018 14:31,07-08-2018 15:27,13-08-2018 00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,08-08-2018 08:38,08-08-2018 08:55,08-08-2018 13:50,17-08-2018 18:06,04-09-2018 00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,18-11-2017 19:28,18-11-2017 19:45,22-11-2017 13:39,02-12-2017 00:28,15-12-2017 00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,13-02-2018 21:18,13-02-2018 22:20,14-02-2018 19:46,16-02-2018 18:17,26-02-2018 00:00

In [62]:
orders_clean.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [7]:
orders_clean.shape

NameError: name 'orders_clean' is not defined

In [8]:
(orders_clean["delivery_days"] < 0).sum()

NameError: name 'orders_clean' is not defined

In [65]:
orders_clean["delay_status"] = np.where(
    orders_clean["delay_days"] > 0,
    "Delayed",
    "On Time/Early"
)

KeyError: 'delay_days'

In [66]:
orders_clean["delay_status"].value_counts()

KeyError: 'delay_status'

In [67]:
orders_clean[
    orders_clean["order_delivered_customer_date"].isnull()
]["order_status"].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [68]:
orders_clean.to_csv(
    "../Cleaned Data/orders_clean.csv",
    index=False
)

In [2]:
import os

os.listdir("../Cleaned Data")

['customers_clean.csv', 'orders_clean.csv']

In [3]:
orders_clean.shape

NameError: name 'orders_clean' is not defined

In [4]:
orders_clean = pd.read_csv("../Cleaned Data/orders_clean.csv")

NameError: name 'pd' is not defined

In [5]:
orders_clean.shape

NameError: name 'orders_clean' is not defined

In [1]:
check_orders = pd.read_csv("../Cleaned Data/orders_clean.csv")

NameError: name 'pd' is not defined

In [6]:
check_orders.shape

NameError: name 'check_orders' is not defined

In [14]:
import pandas as pd
import numpy as np

In [15]:
customers = pd.read_csv("../Raw Data/olist_customers_dataset.csv")
orders = pd.read_csv("../Raw Data/olist_orders_dataset.csv")
order_items = pd.read_csv("../Raw Data/olist_order_items_dataset.csv")
products = pd.read_csv("../Raw Data/olist_products_dataset.csv")
payments = pd.read_csv("../Raw Data/olist_order_payments_dataset.csv")
reviews = pd.read_csv("../Raw Data/olist_order_reviews_dataset.csv")
sellers = pd.read_csv("../Raw Data/olist_sellers_dataset.csv")
geolocation = pd.read_csv("../Raw Data/olist_geolocation_dataset.csv")
category_translation = pd.read_csv("../Raw Data/product_category_name_translation.csv")

In [16]:
import pandas as pd
import numpy as np
import os

In [17]:
orders = pd.read_csv("../Raw Data/olist_orders_dataset.csv")

In [18]:
print(os.listdir("../Cleaned Data"))

['customers_clean.csv', 'orders_clean.csv']

In [19]:
saved_orders = pd.read_csv("../Cleaned Data/orders_clean.csv")
print(saved_orders.shape)
print(saved_orders.columns)

(99441, 8)
Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='object')

In [20]:
saved_orders = pd.read_csv("../Cleaned Data/orders_clean.csv")

print(saved_orders.shape)

(99441, 8)

In [21]:
orders_clean = orders.copy()

In [23]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    orders_clean[col] = pd.to_datetime(
        orders_clean[col],
        format="mixed",
        errors="coerce"
    )

KeyboardInterrupt:

In [24]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    orders_clean[col] = pd.to_datetime(
        orders_clean[col],
        format="mixed",
        errors="coerce"
    )

In [25]:
for col in date_columns:
    orders_clean[col] = pd.to_datetime(
        orders_clean[col],
        format="mixed",
        errors="coerce"
    )

In [26]:
import pandas as pd

print(pd.__version__)

2.3.3

In [27]:
orders_clean = orders.copy()

In [28]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date"
]

for col in date_columns:
    orders_clean[col] = pd.to_datetime(
        orders_clean[col],
        errors="coerce"
    )

In [29]:
orders_clean["order_estimated_delivery_date"] = pd.to_datetime(
    orders_clean["order_estimated_delivery_date"],
    errors="coerce"
)

C:\Users\HP\AppData\Local\Temp\ipykernel_12888\578999017.py:1: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  orders_clean["order_estimated_delivery_date"] = pd.to_datetime(

In [30]:
orders_clean["order_estimated_delivery_date"] = pd.to_datetime(
    orders_clean["order_estimated_delivery_date"],
    dayfirst=True,
    errors="coerce"
)

In [31]:
orders_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       39631 non-null  datetime64[ns]
 4   order_approved_at              39648 non-null  datetime64[ns]
 5   order_delivered_carrier_date   37332 non-null  datetime64[ns]
 6   order_delivered_customer_date  36354 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

In [32]:
orders_clean = orders.copy()

In [33]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    orders_clean[col] = pd.to_datetime(
        orders_clean[col],
        format="mixed",
        dayfirst=True,
        errors="coerce"
    )

In [34]:
orders_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

In [35]:
orders_clean["delivery_days"] = (
    orders_clean["order_delivered_customer_date"]
    - orders_clean["order_purchase_timestamp"]
).dt.days

In [36]:
orders_clean["approval_days"] = (
    orders_clean["order_approved_at"]
    - orders_clean["order_purchase_timestamp"]
).dt.days

In [37]:
orders_clean["delay_days"] = (
    orders_clean["order_delivered_customer_date"]
    - orders_clean["order_estimated_delivery_date"]
).dt.days

In [38]:
import numpy as np

orders_clean["delay_status"] = np.where(
    orders_clean["delay_days"] > 0,
    "Delayed",
    "On Time/Early"
)

In [39]:
orders_clean.shape

(99441, 12)

In [40]:
orders_clean.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_days,approval_days,delay_days,delay_status
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-04 19:55:00,2017-10-10 21:25:00,2017-10-18,8.0,0.0,-8.0,On Time/Early
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:00,2018-07-26 03:24:00,2018-07-26 14:31:00,2018-08-07 15:27:00,2018-08-13,13.0,1.0,-6.0,On Time/Early
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:00,2018-08-08 08:55:00,2018-08-08 13:50:00,2018-08-17 18:06:00,2018-09-04,9.0,0.0,-18.0,On Time/Early
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:00,2017-11-18 19:45:00,2017-11-22 13:39:00,2017-12-02 00:28:00,2017-12-15,13.0,0.0,-13.0,On Time/Early
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:00,2018-02-13 22:20:00,2018-02-14 19:46:00,2018-02-16 18:17:00,2018-02-26,2.0,0.0,-10.0,On Time/Early

In [41]:
orders_clean["delay_status"].value_counts()

delay_status
On Time/Early    92906
Delayed           6535
Name: count, dtype: int64

In [42]:
orders_clean.shape

(99441, 12)

In [43]:
orders_clean.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
delivery_days                    2965
approval_days                     160
delay_days                       2965
delay_status                        0
dtype: int64

In [44]:
orders_clean.duplicated().sum()

np.int64(0)

In [45]:
orders_clean["order_id"].duplicated().sum()

np.int64(0)

In [46]:
orders_clean.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'delivery_days', 'approval_days', 'delay_days', 'delay_status'],
      dtype='object')

In [48]:
orders_clean.to_csv(
    "../Cleaned Data/orders_clean.csv",
    index=False
)

In [49]:


orders_clean.to_csv(
    "../Cleaned Data/orders_clean.csv",
    index=False
)

In [50]:
import os

os.getcwd()

'C:\\Users\\HP\\Downloads\\DA PROJECT\\PYTHON'

In [51]:
os.listdir("../Cleaned Data")

['customers_clean.csv', 'orders_clean.csv']

In [52]:
orders_clean.to_csv(
    "../Cleaned Data/orders_clean_final.csv",
    index=False
)

In [53]:
os.listdir("../Cleaned Data")

['customers_clean.csv', 'orders_clean.csv', 'orders_clean_final.csv']

In [54]:
orders_final_check = pd.read_csv("../Cleaned Data/orders_clean_final.csv")

print(orders_final_check.shape)

print(orders_final_check.columns)

(99441, 12)
Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'delivery_days', 'approval_days', 'delay_days', 'delay_status'],
      dtype='object')

In [55]:
order_items_clean = order_items.copy()

In [56]:
order_items_clean.shape

(112650, 7)

In [57]:
order_items_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [58]:
order_items_clean.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [59]:
order_items_clean.duplicated().sum()

np.int64(0)

In [60]:
order_items_clean.nunique()

order_id               98666
order_item_id             21
product_id             32951
seller_id               3095
shipping_limit_date    54615
price                   5968
freight_value           6999
dtype: int64

In [61]:
order_items_clean.describe()

       order_item_id          price  freight_value
count  112650.000000  112650.000000  112650.000000
mean        1.197834     120.653739      19.990320
std         0.705124     183.633928      15.806405
min         1.000000       0.850000       0.000000
25%         1.000000      39.900000      13.080000
50%         1.000000      74.990000      16.260000
75%         1.000000     134.900000      21.150000
max        21.000000    6735.000000     409.680000

In [62]:
order_items_clean.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [63]:
order_items_clean["shipping_limit_date"] = pd.to_datetime(
    order_items_clean["shipping_limit_date"],
    format="mixed",
    errors="coerce"
)

In [64]:
order_items_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  datetime64[ns]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 6.0+ MB

In [65]:
order_items_clean["shipping_limit_date"].isnull().sum()

np.int64(0)

In [66]:
order_items_clean.nlargest(10,"price")

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
3556,0812eb902a67711a1cb742b3cdaa65ae,1,489ae2aa008f021502940f251d4cce7f,e3b4998c7a498169dc7bce44e6bb6277,2017-02-16 20:37:00,6735.00,194.31
112233,fefacc66af859508bf1a7934eab1e97f,1,69c590f7ffc7bf8db97190b6cb6ed62e,80ceebb4ee9b31afb6c6a916a574a1e2,2018-02-08 04:05:00,6729.00,193.21
107841,f5136e38d1a14a4dbd87dff67da82701,1,1bdf5e6731585cf01aa8169c7028d6ad,ee27a8f15b1dded4d213a468ba4eb391,2017-06-15 02:45:00,6499.00,227.66
74336,a96610ab360d42a2e5335a3998b4718a,1,a6492cc69376c469ab6f61d8f44de961,59417c56835dd8e2e72f91f809cd4092,2017-04-18 13:25:00,4799.00,151.34
11249,199af31afc78c699f0dbf71fb178d4d4,1,c3ed642d592594bb648ff4a04cee2747,59417c56835dd8e2e72f91f809cd4092,2017-09-05 15:50:00,4690.00,74.34
62086,8dbc85d1447242f3b127dda390d56e19,1,259037a6a41845e455183f89c5035f18,c72de06d72748d1a0dfb2125be43ba63,2018-06-28 12:36:00,4590.00,91.78
29193,426a9742b533fc6fed17d1fd6d143d7e,1,a1beef8f3992dbd4cd8726796aa69c53,512d298ac2a96d1931b6bd30aa21f61d,2018-08-16 14:24:00,4399.87,113.45
45843,68101694e5c5dc7330c91e1bbc36214f,1,6cdf8fc1d741c76586d8b6b15e9eef30,ed4acab38528488b65a9a9c603ff024a,2018-05-04 08:27:00,4099.99,75.27
78310,b239ca7cd485940b31882363b52e6674,1,dd113cb02b2af9c8e5787e8f1f0722f6,821fb029fc6e495ca4f08a35d51e53a5,2018-02-08 08:15:00,4059.00,104.51
59137,86c4eab1571921a6a6e248ed312f5a5a,1,6902c1962dd19d540807d0ab8fade5c6,fa1c13f2614d7b5c4749cbc52fecda94,2017-03-23 20:08:00,3999.90,17.01

In [67]:
order_items_clean.nlargest(10,"freight_value")

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
73486,a77e1550db865202c56b19ddc6dc4d53,1,ec31d2a17b299511e7c8627be9337b9b,257e61d3251fb5efb9daadddbc2cf7ca,2018-04-25 06:55:00,979.00,409.68
3303,076d1555fb53a89b0ef4d529e527a0f6,1,a3cd9517ebf5a50dca25acce54f3b171,6fa9202c10491e472dffd59a3e82b2a3,2018-07-08 04:35:00,2338.08,375.28
28044,3fde74c28a3d5d618c00f26d51baafa0,1,a3cd9517ebf5a50dca25acce54f3b171,6fa9202c10491e472dffd59a3e82b2a3,2018-08-22 03:15:00,2338.08,375.28
69797,9f49bd16053df810384e793386312674,1,256a9c364b75753b97bee410c9491ad8,5c030029b5916fed0986310385ec9009,2018-02-08 03:44:00,1149.00,339.59
16731,264a7e199467906c0727394df82d1a6a,1,97c948ebc8c04b26b7bbb095d4228f2a,17f51e7198701186712e53a39c564617,2018-04-23 17:15:00,1050.00,338.30
87936,c7a07ddd52bbe18b61da49a8d89853d3,1,97c948ebc8c04b26b7bbb095d4228f2a,17f51e7198701186712e53a39c564617,2018-07-31 10:45:00,1050.00,322.10
5037,0b6230647ed16f4b3e70282dc4b5b87f,1,46e24ce614899e36617e37ea1e4aa6ff,17f51e7198701186712e53a39c564617,2018-01-06 19:14:00,1050.00,321.88
3584,0822bcde10bb5d023755a71bc8f7797f,1,363a9f5b97bf194da23858be722a7aa5,9596c870880d900012f2e8e6e30d06d7,2018-10-05 23:52:00,990.00,321.46
29787,43bdbd9dc0931d72befdf4765af6c442,1,7e53e051875b2a0c9f22acd8a9a29a20,eeb6de78f79159600292e314a77cbd18,2018-12-07 08:35:00,3089.00,317.47
48320,6ddfbf514959b49b6410c01ad93054bb,1,363a9f5b97bf194da23858be722a7aa5,9596c870880d900012f2e8e6e30d06d7,2017-11-30 15:10:00,1045.00,314.40

In [68]:
order_items_clean["total_amount"] = (
    order_items_clean["price"] +
    order_items_clean["freight_value"]
)

In [69]:
order_items_clean.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total_amount
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:00,58.90,13.29,72.19
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-03-05 11:05:00,239.90,19.93,259.83
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:00,199.00,17.87,216.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:00,12.99,12.79,25.78
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:00,199.90,18.14,218.04

In [70]:
order_items_clean.shape

(112650, 8)

In [71]:
order_items_clean.to_csv(
    "../Cleaned Data/order_items_clean.csv",
    index=False
)

In [72]:
order_items_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  datetime64[ns]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
 7   total_amount         112650 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(3)
memory usage: 6.9+ MB

In [73]:
order_items_clean.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
total_amount           0
dtype: int64

In [74]:
order_items_clean.duplicated().sum()

np.int64(0)

In [75]:
order_items_clean.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total_amount
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:00,58.90,13.29,72.19
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-03-05 11:05:00,239.90,19.93,259.83
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:00,199.00,17.87,216.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:00,12.99,12.79,25.78
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:00,199.90,18.14,218.04

In [76]:
order_items_clean.duplicated(
    subset=["order_id","order_item_id"]
).sum()

np.int64(0)

In [77]:
order_items_clean["shipping_limit_date"] = pd.to_datetime(
    order_items_clean["shipping_limit_date"],
    errors="coerce"
)

In [78]:
order_items_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  datetime64[ns]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
 7   total_amount         112650 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(3)
memory usage: 6.9+ MB

In [79]:
order_items_clean.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
total_amount           0
dtype: int64

In [80]:
order_items_clean.nlargest(10,"price")

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total_amount
3556,0812eb902a67711a1cb742b3cdaa65ae,1,489ae2aa008f021502940f251d4cce7f,e3b4998c7a498169dc7bce44e6bb6277,2017-02-16 20:37:00,6735.00,194.31,6929.31
112233,fefacc66af859508bf1a7934eab1e97f,1,69c590f7ffc7bf8db97190b6cb6ed62e,80ceebb4ee9b31afb6c6a916a574a1e2,2018-02-08 04:05:00,6729.00,193.21,6922.21
107841,f5136e38d1a14a4dbd87dff67da82701,1,1bdf5e6731585cf01aa8169c7028d6ad,ee27a8f15b1dded4d213a468ba4eb391,2017-06-15 02:45:00,6499.00,227.66,6726.66
74336,a96610ab360d42a2e5335a3998b4718a,1,a6492cc69376c469ab6f61d8f44de961,59417c56835dd8e2e72f91f809cd4092,2017-04-18 13:25:00,4799.00,151.34,4950.34
11249,199af31afc78c699f0dbf71fb178d4d4,1,c3ed642d592594bb648ff4a04cee2747,59417c56835dd8e2e72f91f809cd4092,2017-09-05 15:50:00,4690.00,74.34,4764.34
62086,8dbc85d1447242f3b127dda390d56e19,1,259037a6a41845e455183f89c5035f18,c72de06d72748d1a0dfb2125be43ba63,2018-06-28 12:36:00,4590.00,91.78,4681.78
29193,426a9742b533fc6fed17d1fd6d143d7e,1,a1beef8f3992dbd4cd8726796aa69c53,512d298ac2a96d1931b6bd30aa21f61d,2018-08-16 14:24:00,4399.87,113.45,4513.32
45843,68101694e5c5dc7330c91e1bbc36214f,1,6cdf8fc1d741c76586d8b6b15e9eef30,ed4acab38528488b65a9a9c603ff024a,2018-05-04 08:27:00,4099.99,75.27,4175.26
78310,b239ca7cd485940b31882363b52e6674,1,dd113cb02b2af9c8e5787e8f1f0722f6,821fb029fc6e495ca4f08a35d51e53a5,2018-02-08 08:15:00,4059.00,104.51,4163.51
59137,86c4eab1571921a6a6e248ed312f5a5a,1,6902c1962dd19d540807d0ab8fade5c6,fa1c13f2614d7b5c4749cbc52fecda94,2017-03-23 20:08:00,3999.90,17.01,4016.91

In [81]:
order_items_clean.to_csv(
"../Cleaned Data/order_items_clean_final.csv",
index=False
)

In [82]:
import os

os.listdir("../Cleaned Data")

['customers_clean.csv',
 'orders_clean (2).csv',
 'order_items_clean.csv',
 'order_items_clean_final.csv']

In [83]:
products = pd.read_csv("../Raw Data/products.csv")

FileNotFoundError: [Errno 2] No such file or directory: '../Raw Data/products.csv'

In [84]:
import os

os.listdir("../Raw Data")

['olist_customers_dataset.csv',
 'olist_geolocation_dataset.csv',
 'olist_orders_dataset.csv',
 'olist_order_items_dataset.csv',
 'olist_order_payments_dataset.csv',
 'olist_order_reviews_dataset.csv',
 'olist_products_dataset.csv',
 'olist_sellers_dataset.csv',
 'product_category_name_translation.csv']

In [85]:
products = pd.read_csv("../Raw Data/olist_products_dataset.csv")

In [86]:
products.shape

(32951, 9)

In [87]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [88]:
products_clean = products.copy()

In [89]:
os.listdir("../Raw Data")

['olist_customers_dataset.csv',
 'olist_geolocation_dataset.csv',
 'olist_orders_dataset.csv',
 'olist_order_items_dataset.csv',
 'olist_order_payments_dataset.csv',
 'olist_order_reviews_dataset.csv',
 'olist_products_dataset.csv',
 'olist_sellers_dataset.csv',
 'product_category_name_translation.csv']

In [90]:
products_clean["product_id"].duplicated().sum()

np.int64(0)

In [91]:
products_clean.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [92]:
products_clean["product_category_name"] = (
    products_clean["product_category_name"]
    .fillna("unknown")
)

In [93]:
products_clean["product_category_name"].isnull().sum()

np.int64(0)

In [94]:
num_columns = [
    "product_name_lenght",
    "product_description_lenght",
    "product_photos_qty",
    "product_weight_g",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm"
]


for col in num_columns:
    products_clean[col] = (
        products_clean[col]
        .fillna(products_clean[col].median())
    )

In [95]:
products_clean.isnull().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [96]:
Minimum Weight = 0 grams

SyntaxError: invalid syntax (949824492.py, line 1)

In [97]:
(products_clean["product_weight_g"] == 0).sum()

np.int64(4)

In [98]:
products_clean.loc[
    products_clean["product_weight_g"] == 0,
    "product_weight_g"
] = products_clean["product_weight_g"].median()

In [99]:
products_clean.duplicated().sum()

np.int64(0)

In [100]:
products_clean["product_volume_cm3"] = (
    products_clean["product_length_cm"] *
    products_clean["product_height_cm"] *
    products_clean["product_width_cm"]
)

In [101]:
products_clean.shape

(32951, 10)

In [102]:
products_clean.isnull().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
product_volume_cm3            0
dtype: int64

In [103]:
products_clean["product_id"].duplicated().sum()

np.int64(0)

In [104]:
products_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32951 non-null  object
 2   product_name_lenght         32951 non-null  float64
 3   product_description_lenght  32951 non-null  float64
 4   product_photos_qty          32951 non-null  float64
 5   product_weight_g            32951 non-null  float64
 6   product_length_cm           32951 non-null  float64
 7   product_height_cm           32951 non-null  float64
 8   product_width_cm            32951 non-null  float64
 9   product_volume_cm3          32951 non-null  float64
dtypes: float64(8), object(2)
memory usage: 2.5+ MB

In [105]:
products_clean.to_csv(
    "../Cleaned Data/products_clean.csv",
    index=False
)

In [106]:
os.listdir("../Cleaned Data")

['customers_clean.csv',
 'orders_clean (2).csv',
 'order_items_clean.csv',
 'products_clean.csv']

In [107]:
products_clean.rename(
    columns={
        "product_name_lenght": "product_name_length",
        "product_description_lenght": "product_description_length"
    },
    inplace=True
)

In [108]:
products_clean.columns

Index(['product_id', 'product_category_name', 'product_name_length',
       'product_description_length', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'product_volume_cm3'],
      dtype='object')

In [109]:
products_clean.to_csv(
    "../Cleaned Data/products_clean.csv",
    index=False
)

In [110]:
products_check = pd.read_csv("../Cleaned Data/products_clean.csv")

products_check.columns

Index(['product_id', 'product_category_name', 'product_name_length',
       'product_description_length', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'product_volume_cm3'],
      dtype='object')

In [111]:
import os

os.listdir("../Cleaned Data")

['customers_clean.csv',
 'orders_clean (2).csv',
 'order_items_clean.csv',
 'products_clean.csv']

In [112]:
products_check = pd.read_csv("../Cleaned Data/products_clean.csv")

In [113]:
products_check.shape

(32951, 10)

In [114]:
products_check.columns

Index(['product_id', 'product_category_name', 'product_name_length',
       'product_description_length', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'product_volume_cm3'],
      dtype='object')

In [115]:
products_check.isnull().sum()

product_id                    0
product_category_name         0
product_name_length           0
product_description_length    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
product_volume_cm3            0
dtype: int64

In [116]:
import os

os.listdir("../Cleaned Data")

['customers_clean.csv',
 'orders_clean (2).csv',
 'order_items_clean.csv',
 'products_clean.csv']

In [117]:
sellers = pd.read_csv(
"../Raw Data/olist_sellers_dataset.csv"
)

In [118]:
sellers_clean = sellers.copy()

In [119]:
sellers_clean.shape

(3095, 4)

In [120]:
sellers_clean["seller_city"] = (
    sellers_clean["seller_city"]
    .str.lower()
    .str.strip()
)

In [121]:
sellers_clean["seller_state"] = (
    sellers_clean["seller_state"]
    .str.upper()
    .str.strip()
)

In [122]:
sellers_clean.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [123]:
sellers_clean.duplicated().sum()

np.int64(0)

In [124]:
sellers_clean["seller_id"].duplicated().sum()

np.int64(0)

In [125]:
sellers_clean.shape

(3095, 4)

In [126]:
sellers_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

In [127]:
sellers_clean.to_csv(
    "../Cleaned Data/sellers_clean.csv",
    index=False
)

In [128]:
import os

os.listdir("../Cleaned Data")

['customers_clean.csv',
 'orders_clean (2).csv',
 'order_items_clean.csv',
 'products_clean.csv',
 'sellers_clean.csv']

In [129]:
payments = pd.read_csv(
    "../Raw Data/olist_order_payments_dataset.csv"
)

payments_clean = payments.copy()

payments_clean.shape

(103886, 5)

In [130]:
payments_clean.columns

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='object')

In [131]:
payments_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [132]:
payments_clean.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [133]:
payments_clean.duplicated().sum()

np.int64(0)

In [134]:
payments_clean.duplicated(
    subset=["order_id","payment_sequential"]
).sum()

np.int64(0)

In [135]:
payments_clean.nunique()

order_id                99440
payment_sequential         29
payment_type                5
payment_installments       24
payment_value           29077
dtype: int64

In [136]:
payments_clean["payment_type"].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [137]:
payments_clean[
    payments_clean["payment_type"]=="not_defined"
].shape

(3, 5)

In [138]:
payments_clean["payment_type"] = (
    payments_clean["payment_type"]
    .str.lower()
    .str.strip()
)

In [139]:
payments_clean["payment_type"].unique()

array(['credit_card', 'boleto', 'voucher', 'debit_card', 'not_defined'],
      dtype=object)

In [140]:
payments_clean["payment_value"].describe()

count    103886.000000
mean        154.100380
std         217.494064
min           0.000000
25%          56.790000
50%         100.000000
75%         171.837500
max       13664.080000
Name: payment_value, dtype: float64

In [141]:
(payments_clean["payment_value"] == 0).sum()

np.int64(9)

In [142]:
(payments_clean["payment_value"] < 0).sum()

np.int64(0)

In [143]:
payments_clean["payment_installments"].describe()

count    103886.000000
mean          2.853349
std           2.687051
min           0.000000
25%           1.000000
50%           1.000000
75%           4.000000
max          24.000000
Name: payment_installments, dtype: float64

In [144]:
(payments_clean["payment_installments"] <= 0).sum()

np.int64(2)

In [145]:
print("Shape:", payments_clean.shape)

print(
"Missing values:\n",
payments_clean.isnull().sum()
)

print(
"Duplicate rows:",
payments_clean.duplicated().sum()
)

print(
"Duplicate composite keys:",
payments_clean.duplicated(
subset=["order_id","payment_sequential"]
).sum()
)

Shape: (103886, 5)
Missing values:
 order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64
Duplicate rows: 0
Duplicate composite keys: 0

In [146]:
payments_clean[
    payments_clean["payment_installments"] <= 0
]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94

In [147]:
payments_clean.loc[
    payments_clean["payment_installments"] == 0,
    "payment_installments"
] = 1

In [148]:
(payments_clean["payment_installments"] <= 0).sum()

np.int64(0)

In [149]:
payments_clean["payment_type"].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [150]:
payments_clean["payment_value"].describe()

count    103886.000000
mean        154.100380
std         217.494064
min           0.000000
25%          56.790000
50%         100.000000
75%         171.837500
max       13664.080000
Name: payment_value, dtype: float64

In [151]:
(payments_clean["payment_value"] < 0).sum()

np.int64(0)

In [152]:
print("Shape:", payments_clean.shape)

print("\nMissing Values:")
print(payments_clean.isnull().sum())

print("\nDuplicate Rows:")
print(payments_clean.duplicated().sum())

print("\nDuplicate Composite Keys:")
print(
    payments_clean.duplicated(
        subset=["order_id","payment_sequential"]
    ).sum()
)

print("\nZero Installments:")
print(
    (payments_clean["payment_installments"] <= 0).sum()
)

Shape: (103886, 5)

Missing Values:
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

Duplicate Rows:
0

Duplicate Composite Keys:
0

Zero Installments:
0

In [153]:
payments_clean.to_csv(
    "../Cleaned Data/payments_clean.csv",
    index=False
)

In [154]:
import os

os.listdir("../Cleaned Data")

['customers_clean.csv',
 'orders_clean (2).csv',
 'order_items_clean.csv',
 'payments_clean.csv',
 'products_clean.csv',
 'sellers_clean.csv']

In [155]:
reviews_clean = reviews.copy()

In [156]:
import os

os.listdir("../Cleaned Data")

['customers_clean.csv',
 'orders_clean.csv',
 'order_items_clean.csv',
 'payments_clean.csv',
 'products_clean.csv',
 'sellers_clean.csv']

In [157]:
reviews = pd.read_csv(
    "../Raw Data/olist_order_reviews_dataset.csv"
)

reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,18-01-2018 00:00,18-01-2018 21:46
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,10-03-2018 00:00,11-03-2018 03:05
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,17-02-2018 00:00,18-02-2018 14:36
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,21-04-2017 00:00,21-04-2017 22:02
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,01-03-2018 00:00,02-03-2018 10:26

In [158]:
reviews_clean = reviews.copy()

In [159]:
reviews_clean.shape

(99224, 7)

In [160]:
reviews_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

In [161]:
reviews_clean.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [162]:
reviews_clean.duplicated().sum()

np.int64(0)

In [163]:
reviews_clean["review_id"].duplicated().sum()

np.int64(814)

In [164]:
reviews_clean["review_score"].value_counts().sort_index()

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

In [165]:
text_columns = [
    "review_comment_title",
    "review_comment_message"
]


for col in text_columns:
    reviews_clean[col] = (
        reviews_clean[col]
        .fillna("No Comment")
        .str.lower()
        .str.strip()
    )

In [166]:
date_columns = [
    "review_creation_date",
    "review_answer_timestamp"
]


for col in date_columns:
    reviews_clean[col] = pd.to_datetime(
        reviews_clean[col],
        errors="coerce"
    )

C:\Users\HP\AppData\Local\Temp\ipykernel_12888\2109199591.py:8: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  reviews_clean[col] = pd.to_datetime(
C:\Users\HP\AppData\Local\Temp\ipykernel_12888\2109199591.py:8: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  reviews_clean[col] = pd.to_datetime(

In [167]:
date_columns = [
    "review_creation_date",
    "review_answer_timestamp"
]


for col in date_columns:
    reviews_clean[col] = pd.to_datetime(
        reviews_clean[col],
        dayfirst=True,
        errors="coerce"
    )

In [168]:
reviews_clean.isnull().sum()

review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [169]:
reviews_clean.duplicated().sum()

np.int64(0)

In [170]:
reviews_clean["review_id"].duplicated().sum()

np.int64(814)

In [171]:
reviews_clean["order_id"].duplicated().sum()

np.int64(551)

In [172]:
reviews_clean.shape

(99224, 7)

In [173]:
print("Shape:", reviews_clean.shape)

print("\nMissing Values:")
print(reviews_clean.isnull().sum())

print("\nDuplicate Rows:")
print(reviews_clean.duplicated().sum())

print("\nDuplicate Review IDs:")
print(reviews_clean["review_id"].duplicated().sum())

print("\nReview Score Range:")
print(
    reviews_clean["review_score"].min(),
    reviews_clean["review_score"].max()
)

Shape: (99224, 7)

Missing Values:
review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

Duplicate Rows:
0

Duplicate Review IDs:
814

Review Score Range:
1 5

In [174]:
reviews_clean[
    reviews_clean["review_id"].duplicated(keep=False)
].head(10)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
200,28642ce6250b94cc72bc85960aec6c62,e239d280236cdd3c40cb2c033f681d1c,5,no comment,no comment,2018-03-25,2018-03-25 21:03:00
344,a0a641414ff718ca079b3967ef5c2495,169d7e0fd71d624d306f132acd791cbe,5,no comment,no comment,2018-03-04,2018-03-06 20:12:00
346,f4d74b17cd63ee35efa82cd2567de911,f269e83a82f64baa3de97c2ebf3358f6,3,no comment,"a embalagem deixou a desejar, por pouco o prod...",2018-01-12,2018-01-13 18:46:00
360,ecbaf1fce7d2c09bfab46f89065afeaf,2451b9756f310d4cff5c7987b393870d,5,no comment,no comment,2017-07-27,2017-07-28 16:57:00
393,6b1de94de0f4bd84dfc4136818242faa,92acf87839903a94aeca0e5040d99acb,5,no comment,no comment,2018-02-16,2018-02-19 19:04:00
433,957011305e7a4b6c8a266eeeb8e0316d,54b4da510fed5dc3cf3e7a8e50a5f224,4,no comment,no comment,2018-03-10,2018-03-10 23:35:00
508,b34f4a786bf00b7c8486141ba482783b,b2501eb5c292d415f52576b3d4b5de74,3,no comment,no comment,2017-05-04,2017-05-22 12:02:00
661,d433c252647c51309432ca0b763f969b,448795135b904d057254f5fd0d5a6a4c,1,no comment,no comment,2017-09-03,2017-09-06 16:11:00
723,5f35bbde2b32b8617aab15b7a9a0ae24,ba568688e2f462d7c44a3fdc62e6456f,4,no comment,no comment,2017-11-26,2017-11-27 21:00:00
764,c5976a5a98e854fb23d7e03c6754ae60,2002ea16e75277eaa0b5d78632048540,5,no comment,no comment,2017-08-08,2017-08-10 11:11:00

In [175]:
reviews_clean[
    reviews_clean["review_id"].duplicated(keep=False)
].shape

(1603, 7)

In [176]:
reviews_clean[
    reviews_clean["review_id"].duplicated(keep=False)
].head(10)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
200,28642ce6250b94cc72bc85960aec6c62,e239d280236cdd3c40cb2c033f681d1c,5,no comment,no comment,2018-03-25,2018-03-25 21:03:00
344,a0a641414ff718ca079b3967ef5c2495,169d7e0fd71d624d306f132acd791cbe,5,no comment,no comment,2018-03-04,2018-03-06 20:12:00
346,f4d74b17cd63ee35efa82cd2567de911,f269e83a82f64baa3de97c2ebf3358f6,3,no comment,"a embalagem deixou a desejar, por pouco o prod...",2018-01-12,2018-01-13 18:46:00
360,ecbaf1fce7d2c09bfab46f89065afeaf,2451b9756f310d4cff5c7987b393870d,5,no comment,no comment,2017-07-27,2017-07-28 16:57:00
393,6b1de94de0f4bd84dfc4136818242faa,92acf87839903a94aeca0e5040d99acb,5,no comment,no comment,2018-02-16,2018-02-19 19:04:00
433,957011305e7a4b6c8a266eeeb8e0316d,54b4da510fed5dc3cf3e7a8e50a5f224,4,no comment,no comment,2018-03-10,2018-03-10 23:35:00
508,b34f4a786bf00b7c8486141ba482783b,b2501eb5c292d415f52576b3d4b5de74,3,no comment,no comment,2017-05-04,2017-05-22 12:02:00
661,d433c252647c51309432ca0b763f969b,448795135b904d057254f5fd0d5a6a4c,1,no comment,no comment,2017-09-03,2017-09-06 16:11:00
723,5f35bbde2b32b8617aab15b7a9a0ae24,ba568688e2f462d7c44a3fdc62e6456f,4,no comment,no comment,2017-11-26,2017-11-27 21:00:00
764,c5976a5a98e854fb23d7e03c6754ae60,2002ea16e75277eaa0b5d78632048540,5,no comment,no comment,2017-08-08,2017-08-10 11:11:00

In [177]:
reviews_clean.to_csv(
    "../Cleaned Data/reviews_clean.csv",
    index=False
)

In [178]:
import os

os.listdir("../Cleaned Data")

['customers_clean.csv',
 'orders_clean.csv',
 'order_items_clean.csv',
 'payments_clean.csv',
 'products_clean.csv',
 'reviews_clean.csv',
 'sellers_clean.csv']

In [179]:
geolocation = pd.read_csv("../Raw Data/olist_geolocation_dataset.csv")

In [180]:
geolocation.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [181]:
geolocation.tail()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
1000158,99950,-28.068639,-52.010705,tapejara,RS
1000159,99900,-27.877125,-52.224882,getulio vargas,RS
1000160,99950,-28.071855,-52.014716,tapejara,RS
1000161,99980,-28.388932,-51.846871,david canabarro,RS
1000162,99950,-28.070104,-52.018658,tapejara,RS

In [182]:
geolocation_clean = geolocation.copy()

In [183]:
geolocation_clean.shape

(1000163, 5)

In [184]:
geolocation_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

In [185]:
geolocation_clean.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [186]:
geolocation_clean.duplicated().sum()

np.int64(261836)

In [187]:
geolocation_clean[
    geolocation_clean.duplicated()
].head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
15,1046,-23.546081,-46.644820,sao paulo,SP
44,1046,-23.546081,-46.644820,sao paulo,SP
65,1046,-23.546081,-46.644820,sao paulo,SP
66,1009,-23.546935,-46.636588,sao paulo,SP
67,1046,-23.546081,-46.644820,sao paulo,SP

In [188]:
geolocation_clean["geolocation_zip_code_prefix"].duplicated().sum()

np.int64(981148)

In [189]:
import unicodedata

In [190]:
def remove_accents(text):
    return ''.join(
        c for c in unicodedata.normalize('NFKD', text)
        if not unicodedata.combining(c)
    )

In [191]:
geolocation_clean["geolocation_city"] = (
    geolocation_clean["geolocation_city"]
    .str.lower()
    .str.strip()
    .apply(remove_accents)
)

In [192]:
geolocation_clean["geolocation_state"] = (
    geolocation_clean["geolocation_state"]
    .str.upper()
    .str.strip()
)

In [193]:
geolocation_clean.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [194]:
geolocation_clean["geolocation_city"].nunique()

5968

In [195]:
geolocation_clean["geolocation_state"].unique()

array(['SP', 'RN', 'AC', 'RJ', 'ES', 'MG', 'BA', 'SE', 'PE', 'AL', 'PB',
       'CE', 'PI', 'MA', 'PA', 'AP', 'AM', 'RR', 'DF', 'GO', 'RO', 'TO',
       'MT', 'MS', 'RS', 'PR', 'SC'], dtype=object)

In [196]:
print("Shape:", geolocation_clean.shape)

print("\nMissing:")
print(geolocation_clean.isnull().sum())

print("\nDuplicate Rows:")
print(geolocation_clean.duplicated().sum())

Shape: (1000163, 5)

Missing:
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

Duplicate Rows:
279673

In [197]:
geolocation_clean.to_csv(
    "../Cleaned Data/geolocation_clean.csv",
    index=False
)

In [198]:
import os

os.listdir("../Cleaned Data")

['customers_clean.csv',
 'geolocation_clean.csv',
 'orders_clean.csv',
 'order_items_clean.csv',
 'payments_clean.csv',
 'products_clean.csv',
 'reviews_clean.csv',
 'sellers_clean.csv']

In [199]:
category_translation = pd.read_csv(
    "../Raw Data/product_category_name_translation.csv"
)

In [200]:
category_translation.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [201]:
category_translation_clean = category_translation.copy()

In [202]:
category_translation_clean.shape

(71, 2)

In [203]:
category_translation_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

In [204]:
category_translation_clean.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [205]:
category_translation_clean.duplicated().sum()

np.int64(0)

In [206]:
product_category_name

NameError: name 'product_category_name' is not defined

In [207]:
category_translation_clean[
    "product_category_name"
].duplicated().sum()

np.int64(0)

In [208]:
category_translation_clean["product_category_name"] = (
    category_translation_clean["product_category_name"]
    .str.lower()
    .str.strip()
)


category_translation_clean["product_category_name_english"] = (
    category_translation_clean["product_category_name_english"]
    .str.lower()
    .str.strip()
)

In [209]:
missing_categories = set(
    products["product_category_name"].dropna()
) - set(
    category_translation_clean["product_category_name"]
)

missing_categories

{'pc_gamer', 'portateis_cozinha_e_preparadores_de_alimentos'}

In [210]:
print("Shape:", category_translation_clean.shape)

print("\nMissing Values:")
print(category_translation_clean.isnull().sum())

print("\nDuplicate Rows:")
print(category_translation_clean.duplicated().sum())

print("\nDuplicate Category Names:")
print(
    category_translation_clean[
        "product_category_name"
    ].duplicated().sum()
)

Shape: (71, 2)

Missing Values:
product_category_name            0
product_category_name_english    0
dtype: int64

Duplicate Rows:
0

Duplicate Category Names:
0

In [211]:
category_translation_clean.to_csv(
    "../Cleaned Data/category_translation_clean.csv",
    index=False
)

In [212]:
import os

os.listdir("../Cleaned Data")

['category_translation_clean.csv',
 'customers_clean.csv',
 'geolocation_clean.csv',
 'orders_clean.csv',
 'order_items_clean.csv',
 'payments_clean.csv',
 'products_clean.csv',
 'reviews_clean.csv',
 'sellers_clean.csv']

In [213]:
reviews_clean[
    reviews_clean["review_comment_title"].isna()
]

Empty DataFrame
Columns: [review_id, order_id, review_score, review_comment_title, review_comment_message, review_creation_date, review_answer_timestamp]
Index: []

In [214]:
reviews_clean[
    reviews_clean["review_comment_message"].isna()
]

Empty DataFrame
Columns: [review_id, order_id, review_score, review_comment_title, review_comment_message, review_creation_date, review_answer_timestamp]
Index: []

In [215]:
reviews_clean.isnull().sum()

review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [216]:
reviews_clean.to_csv(
    "../Cleaned Data/reviews_clean.csv",
    index=False
)

In [217]:
import os

os.listdir("../Cleaned Data")

['category_translation_clean.csv',
 'customers_clean.csv',
 'geolocation_clean.csv',
 'orders_clean.csv',
 'order_items_clean.csv',
 'payments_clean.csv',
 'products_clean.csv',
 'reviews_clean.csv',
 'sellers_clean.csv']

In [218]:
reviews_clean.isnull().sum()

review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [219]:
pd.read_csv("../Cleaned Data/reviews_clean.csv").isnull().sum()

review_id                   0
order_id                    0
review_score                0
review_comment_title        2
review_comment_message     28
review_creation_date        0
review_answer_timestamp     0
dtype: int64

In [220]:
reviews_clean["review_comment_title"] = (
    reviews_clean["review_comment_title"]
    .astype(str)
    .replace(["nan", "NaN", "None", ""], "No Comment")
)


reviews_clean["review_comment_message"] = (
    reviews_clean["review_comment_message"]
    .astype(str)
    .replace(["nan", "NaN", "None", ""], "No Comment")
)

In [221]:
reviews_clean.isnull().sum()

review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [222]:
reviews_clean.to_csv(
    "../Cleaned Data/reviews_clean.csv",
    index=False,
    na_rep="No Comment"
)

In [223]:
test_reviews = pd.read_csv("../Cleaned Data/reviews_clean.csv")

test_reviews.isnull().sum()

review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     1
review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [224]:
reviews_clean["review_comment_message"] = (
    reviews_clean["review_comment_message"]
    .fillna("No Comment")
    .replace("", "No Comment")
)

In [225]:
reviews_clean["review_comment_title"] = (
    reviews_clean["review_comment_title"]
    .fillna("No Comment")
    .replace("", "No Comment")
)

In [226]:
reviews_clean.isnull().sum()

review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [227]:
reviews_clean.to_csv(
    "../Cleaned Data/reviews_clean.csv",
    index=False,
    na_rep="No Comment"
)

In [228]:
test_reviews = pd.read_csv("../Cleaned Data/reviews_clean.csv")

test_reviews.isnull().sum()

review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     1
review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [229]:
reviews_clean = pd.read_csv("../Cleaned Data/reviews_clean.csv")

In [230]:
reviews_clean["review_comment_message"] = (
    reviews_clean["review_comment_message"]
    .fillna("No Comment")
)

In [231]:
reviews_clean["review_comment_message"].isnull().sum()

np.int64(0)

In [232]:
reviews_clean.to_csv(
    "../Cleaned Data/reviews_clean.csv",
    index=False
)

In [233]:
check = pd.read_csv("../Cleaned Data/reviews_clean.csv")

check.isnull().sum()

review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [1]:
orders_clean[['delivery_days','delay_days']].isnull().sum()

NameError: name 'orders_clean' is not defined

In [2]:
import os

os.listdir("../Cleaned Data")

['category_translation_clean.csv',
 'customers_clean.csv',
 'geolocation_clean.csv',
 'orders_clean.csv',
 'order_items_clean.csv',
 'payments_clean.csv',
 'products_clean.csv',
 'reviews_clean.csv',
 'sellers_clean.csv']

In [3]:
orders_clean[['delivery_days','delay_days']].isnull().sum()

NameError: name 'orders_clean' is not defined

In [4]:
import pandas as pd

orders_clean = pd.read_csv(
    r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\orders_clean.csv"
)

In [5]:
orders_clean[['delivery_days','delay_days']].dtypes

delivery_days    float64
delay_days       float64
dtype: object

In [6]:
orders_clean['delivery_days'].unique()

array([  8.,  13.,   9.,   2.,  16.,  nan,  18.,  12.,   5.,   4.,  11.,
        17.,   6.,  21.,  28.,  14.,  30.,  22.,   1.,  20.,   7.,  10.,
        33.,   3.,  19.,  24.,  23.,  36.,  56.,  54.,  15.,  27.,  26.,
        81.,  31.,  32.,  34.,  25.,   0.,  59.,  38.,  49.,  40.,  29.,
        41.,  35.,  45.,  37.,  75.,  39.,  57.,  46.,  48.,  44.,  66.,
        74.,  51., 110.,  53.,  47.,  42.,  89.,  63., 105., 143.,  43.,
        55.,  70., 132.,  80.,  68.,  84.,  62.,  50.,  96.,  52., 106.,
       191.,  83.,  58.,  67.,  71., 131., 104.,  97.,  60.,  65., 148.,
        61.,  69., 136., 209.,  78., 107.,  73.,  77., 100.,  64.,  98.,
        76.,  72., 130., 165., 168., 186., 108., 126.,  79.,  85., 135.,
       117., 194., 141., 175.,  88., 118., 103.,  86., 138., 145.,  91.,
        82., 166.,  99., 102., 101.,  87., 188., 208., 115., 195., 187.,
       174., 181.,  94.,  92., 167.,  90., 146., 124., 182., 172., 109.,
       189., 173., 133., 142.])

In [7]:
orders_clean['delay_days'].unique()

array([  -8.,   -6.,  -18.,  -13.,  -10.,   nan,  -12.,  -32.,   -7.,
         -9.,  -20.,  -29.,  -17.,  -21.,  -14.,  -15.,   11.,  -26.,
         -4.,    9.,   -5.,    0.,  -16.,    7.,  -31.,  -11.,  -27.,
          1.,  -28.,  -19.,   -2.,   -1.,   -3.,  -24.,   17.,  -35.,
         32.,  -22.,    6.,  -23.,  -33.,   49.,  -25.,    3.,  -34.,
        -52.,  -42.,    5.,    4.,   33.,   15.,   16.,  -37.,  -30.,
         13.,    2.,   20.,   47.,  -47.,   29.,    8.,   10.,  -43.,
        -39.,  -36.,  -48.,  -46.,   27.,   12.,  -50.,   48.,  -40.,
         73.,   35.,   21.,   19.,  -41.,  -45.,  -60.,  -38.,   14.,
         30.,   34.,   18.,   91.,  -54.,  112.,  -44.,   28.,   25.,
         45.,  109.,   63.,   46.,   66.,   23.,  -49.,  -62.,   26.,
         22.,   24.,   39.,   74.,  -56.,   41.,  -69.,  -55.,   36.,
        -64.,   53.,   38.,   60.,  -51.,  175.,   55.,   31.,  -53.,
         40.,  104.,   96.,   70.,   37.,   51.,  -68., -140.,  126.,
         58.,   43.,  181.,   78.,   54.,   50.,   57.,  -65.,   44.,
        -58.,   77.,  -57.,   69.,  143.,  134.,  -75.,  153.,   81.,
        -77.,   80.,  -73.,  100.,  -78.,  132.,  161.,  -61.,  111.,
       -147.,   42.,  105.,   75.,   85.,   82.,  121.,   52.,  123.,
         83.,   65.,   67.,   79.,  159.,  -66.,  -71.,  188.,  106.,
       -135.,  -59.,   97.,  165.,  144.,  -83.,  137.,  152., -109.,
         56.,  162.,  155.,  119.,   68.,  -84.,  -76.,   59.,   88.,
        167.,  138.,   76., -124.,  166.,  -63.,   72.,   94.,  110.,
        -67.])

In [8]:
orders_clean[['delivery_days','delay_days']].isnull().sum()

delivery_days    2965
delay_days       2965
dtype: int64

In [9]:
print(df_orders.columns)

NameError: name 'df_orders' is not defined

In [10]:
orders_clean[
    orders_clean['delivery_days'].isnull()
][['order_status',
   'order_delivered_customer_date',
   'order_estimated_delivery_date',
   'delivery_days',
   'delay_days']]

,order_status,order_delivered_customer_date,order_estimated_delivery_date,delivery_days,delay_days
6,invoiced,NaN,2017-05-09,NaN,NaN
44,shipped,NaN,2018-06-28,NaN,NaN
103,invoiced,NaN,2018-08-21,NaN,NaN
128,processing,NaN,2017-10-03,NaN,NaN
154,shipped,NaN,2018-02-07,NaN,NaN
...,...,...,...,...,...
99283,canceled,NaN,2018-10-01,NaN,NaN
99313,processing,NaN,2018-02-06,NaN,NaN
99347,canceled,NaN,2018-09-27,NaN,NaN
99348,unavailable,NaN,2017-09-15,NaN,NaN
99415,unavailable,NaN,2017-10-23,NaN,NaN

In [11]:
orders_clean.to_csv(
    "orders_clean.csv",
    index=False,
    na_rep=""
)

In [12]:
import pandas as pd

orders_test = pd.read_csv("orders_clean.csv")

In [13]:
orders_test[['delivery_days','delay_days']].dtypes

delivery_days    float64
delay_days       float64
dtype: object

In [14]:
orders_test[['delivery_days','delay_days']].isnull().sum()

delivery_days    2965
delay_days       2965
dtype: int64

In [15]:
import pandas as pd

check_orders = pd.read_csv(
    r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\orders_clean.csv"
)

In [16]:
check_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_days,approval_days,delay_days,delay_status
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-04 19:55:00,2017-10-10 21:25:00,2017-10-18,8.0,0.0,-8.0,On Time/Early
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:00,2018-07-26 03:24:00,2018-07-26 14:31:00,2018-08-07 15:27:00,2018-08-13,13.0,1.0,-6.0,On Time/Early
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:00,2018-08-08 08:55:00,2018-08-08 13:50:00,2018-08-17 18:06:00,2018-09-04,9.0,0.0,-18.0,On Time/Early
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:00,2017-11-18 19:45:00,2017-11-22 13:39:00,2017-12-02 00:28:00,2017-12-15,13.0,0.0,-13.0,On Time/Early
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:00,2018-02-13 22:20:00,2018-02-14 19:46:00,2018-02-16 18:17:00,2018-02-26,2.0,0.0,-10.0,On Time/Early

In [17]:
check_orders[['delivery_days','delay_days']].isnull().sum()

delivery_days    2965
delay_days       2965
dtype: int64

In [18]:
check_orders.dtypes

order_id                          object
customer_id                       object
order_status                      object
order_purchase_timestamp          object
order_approved_at                 object
order_delivered_carrier_date      object
order_delivered_customer_date     object
order_estimated_delivery_date     object
delivery_days                    float64
approval_days                    float64
delay_days                       float64
delay_status                      object
dtype: object

In [19]:
orders_clean['approval_days'].unique()

array([  0.,   1.,   2.,   5.,   3.,   4.,  nan,   6.,  10.,  32.,   8.,
         7.,  11.,  23.,  12.,  13., 187.,   9.,  28.,  30.,  60.,  16.])

In [20]:
orders_clean['approval_days'].dtype

dtype('float64')

In [21]:
orders_clean['approval_days'].unique()

array([  0.,   1.,   2.,   5.,   3.,   4.,  nan,   6.,  10.,  32.,   8.,
         7.,  11.,  23.,  12.,  13., 187.,   9.,  28.,  30.,  60.,  16.])

In [22]:
orders_clean['approval_days'].isnull().sum()

np.int64(160)

In [23]:
orders_clean[
    pd.to_numeric(orders_clean['approval_days'], errors='coerce').isna()
    & orders_clean['approval_days'].notna()
]['approval_days'].unique()

array([], dtype=float64)

In [24]:
import pandas as pd

payments_clean = pd.read_csv(
    r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\payments_clean.csv"
)

payments_clean.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [25]:
payments_clean.dtypes

order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

In [26]:
products_clean.head()

NameError: name 'products_clean' is not defined

In [27]:
import pandas as pd

In [28]:
products_clean = pd.read_csv(
    r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\products_clean.csv"
)

In [29]:
products_clean.head()

,product_id,product_category_name,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_volume_cm3
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,2240.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,10800.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0,2430.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0,2704.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0,4420.0

In [30]:
products_clean.dtypes

product_id                     object
product_category_name          object
product_name_length           float64
product_description_length    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
product_volume_cm3            float64
dtype: object

In [31]:
products_clean.shape

(32951, 10)

In [32]:
products_clean.columns

Index(['product_id', 'product_category_name', 'product_name_length',
       'product_description_length', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'product_volume_cm3'],
      dtype='object')

In [33]:
products_clean.isnull().sum()

product_id                    0
product_category_name         0
product_name_length           0
product_description_length    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
product_volume_cm3            0
dtype: int64

In [34]:
products_clean.duplicated().sum()

np.int64(0)

In [35]:
sellers_clean = pd.read_csv(
    r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\sellers_clean.csv"
)

sellers_clean.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [36]:
sellers_clean.shape
sellers_clean.columns
sellers_clean.dtypes
sellers_clean.isnull().sum()
sellers_clean.duplicated().sum()

np.int64(0)

In [37]:
sellers_clean.columns

Index(['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state'], dtype='object')

In [38]:
sellers_clean.shape

(3095, 4)

In [39]:
sellers_clean.dtypes

seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

In [40]:
sellers_clean.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [41]:
sellers_clean.duplicated().sum()

np.int64(0)

In [42]:
geolocation_clean = pd.read_csv(
    r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\geolocation_clean.csv"
)

geolocation_clean.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [43]:
geolocation_clean.shape

(1000163, 5)

In [44]:
geolocation_clean.columns

Index(['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng',
       'geolocation_city', 'geolocation_state'],
      dtype='object')

In [45]:
geolocation_clean.dtypes

geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object

In [46]:
geolocation_clean.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [47]:
geolocation_clean.duplicated().sum()

np.int64(279673)

In [49]:
import pandas as pd

category_clean = pd.read_csv(
    r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\category_translation_clean.csv"
)

category_clean.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [50]:
category_clean.shape

(71, 2)

In [51]:
category_clean.columns

Index(['product_category_name', 'product_category_name_english'], dtype='object')

In [52]:
category_clean.dtypes

product_category_name            object
product_category_name_english    object
dtype: object

In [53]:
category_clean.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [54]:
category_clean.duplicated().sum()

np.int64(0)

In [55]:
import pandas as pd

reviews_clean = pd.read_csv(
    r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\reviews_clean.csv"
)

reviews_clean.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,no comment,no comment,2018-01-18 00:00:00,2018-01-18 21:46:00
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,no comment,no comment,2018-03-10 00:00:00,2018-03-11 03:05:00
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,no comment,no comment,2018-02-17 00:00:00,2018-02-18 14:36:00
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,no comment,recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:00
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,no comment,parabéns lojas lannister adorei comprar pela i...,2018-03-01 00:00:00,2018-03-02 10:26:00

In [56]:
reviews_clean.shape

(99224, 7)

In [57]:
reviews_clean.columns

Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='object')

In [58]:
reviews_clean.dtypes

review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object

In [59]:
reviews_clean.isnull().sum()

review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [60]:
reviews_clean.duplicated().sum()

np.int64(0)

In [61]:
reviews_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     99224 non-null  object
 4   review_comment_message   99224 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

In [62]:
reviews_clean['review_score'].unique()

array([4, 5, 1, 3, 2])

In [63]:
reviews_clean.shape[0]

99224

In [64]:
reviews.shape

NameError: name 'reviews' is not defined

In [65]:
reviews_clean.shape

(99224, 7)

In [66]:
reviews_clean['review_id'].to_csv('python_review_ids.csv', index=False)

In [67]:
import pandas as pd

# MySQL exported CSV file
mysql_reviews = pd.read_csv(
    r"C:\Users\HP\Downloads\DA PROJECT\SQL\reviews_mysql_export.csv"
)

# Your cleaned Python dataframe
python_reviews = reviews_clean.copy()

print("MySQL table:", mysql_reviews.shape)
print("Python table:", python_reviews.shape)

MySQL table: (1000, 1)
Python table: (99224, 7)

In [68]:
print(mysql_reviews.columns)
print(python_reviews.columns)

Index(['review_id'], dtype='object')
Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='object')

In [69]:
print(mysql_reviews.columns)

Index(['review_id'], dtype='object')

In [70]:
difference = python_reviews.merge(
    mysql_reviews,
    how="outer",
    indicator=True
)

missing_rows = difference[difference["_merge"] == "left_only"]

missing_rows

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,_merge
0,0001239bc1de2e33cb583967c2ca4c67,fc046d7776171871436844218f817d7d,5,no comment,no comment,2018-03-20 00:00:00,2018-03-20 18:36:00,left_only
1,0001cc6860aeaf5b9017fe4131a52e62,d4665434b01caa9dc3e3e78b3eb3593e,5,no comment,no comment,2018-06-22 00:00:00,2018-06-26 13:51:00,left_only
2,00020c7512a52e92212f12d3e37513c0,e28abf2eb2f1fbcbdc2dd0cd9a561671,5,entrega rápida!,a entrega foi super rápida e o pendente é lind...,2018-04-25 00:00:00,2018-04-26 14:55:00,left_only
3,00032b0141443497c898b3093690af51,04fb47576993a3cb0c12d4b25eab6e4e,5,no comment,no comment,2017-05-30 00:00:00,2017-06-01 23:28:00,left_only
4,00034d88989f9a4c393bdcaec301537f,5f358d797a49fe2f24352f73426215f6,5,no comment,no comment,2017-08-12 00:00:00,2017-08-13 19:56:00,left_only
...,...,...,...,...,...,...,...,...
99219,fffcfa6087cd3b651c68252342f13cb9,4069c489933782af79afcd3a0e4d693c,4,no comment,no comment,2017-07-14 00:00:00,2017-07-15 02:14:00,left_only
99220,fffd24e2cf1ca4ee917e2f05be3c01fb,0efaa1dd18856769a1bcc489004fbe3b,5,no comment,no comment,2017-11-25 00:00:00,2017-11-25 21:23:00,left_only
99221,fffd68e8a9fb73a56a2f504011b0f1f1,fceb38f42fbf13b53a6253648c8d47cf,1,no comment,produto muito ruim.,2017-05-31 00:00:00,2017-06-02 23:21:00,left_only
99222,fffee432d53abd67b5b0fd4fc290d8c3,9a54562498faf18f39a0e387976e11a5,5,no comment,no comment,2017-10-25 00:00:00,2017-10-26 08:17:00,left_only
99223,fffefe7a48d22f7b32046421062219d1,1061bc32577c6b8beb107bf1b5a65175,5,no comment,no comment,2017-10-28 00:00:00,2017-10-30 21:43:00,left_only

In [78]:
import pandas as pd

mysql_reviews = pd.read_csv(
    r"C:\Users\HP\Downloads\DA PROJECT\SQL\reviews_mysql_export.csv"
)

print(mysql_reviews.shape)
print(mysql_reviews.columns)
print(mysql_reviews.head())

ParserError: Error tokenizing data. C error: Expected 7 fields in line 1587, saw 8

In [79]:
import pandas as pd

mysql_reviews = pd.read_csv(
    r"C:\Users\HP\Downloads\DA PROJECT\SQL\reviews_mysql_export.csv",
    sep=",",
    quotechar='"',
    encoding="utf-8",
    on_bad_lines="skip"
)

print(mysql_reviews.shape)
print(mysql_reviews.columns)
mysql_reviews.head()

(99180, 7)
Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='object')

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,no comment,no comment,2018-01-18 00:00:00,2018-01-18 21:46:00
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,no comment,no comment,2018-03-10 00:00:00,2018-03-11 03:05:00
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,no comment,no comment,2018-02-17 00:00:00,2018-02-18 14:36:00
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,no comment,recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:00
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,no comment,parabéns lojas lannister adorei comprar pela i...,2018-03-01 00:00:00,2018-03-02 10:26:00

In [80]:
difference = python_reviews.merge(
    mysql_reviews,
    how="outer",
    indicator=True
)

missing_rows = difference[difference["_merge"] == "left_only"]

missing_rows.shape

ValueError: You are trying to merge on int64 and object columns for key 'review_score'. If you wish to proceed you should use pd.concat

In [81]:
import pandas as pd

python_reviews = pd.read_csv(
    r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\reviews_clean.csv"
)

mysql_reviews = pd.read_csv(
    r"C:\Users\HP\Downloads\DA PROJECT\SQL\reviews_mysql_export.csv",
    quotechar='"',
    engine="python"
)

print("Python table:", python_reviews.shape)
print("MySQL table:", mysql_reviews.shape)

ParserError: ',' expected after '"'

In [82]:
import pandas as pd

python_reviews = pd.read_csv(
    r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\reviews_clean.csv"
)

mysql_reviews = pd.read_csv(
    r"C:\Users\HP\Downloads\DA PROJECT\SQL\reviews_mysql_export.csv",
    sep=",",
    engine="python",
    quotechar='"',
    escapechar="\\",
    on_bad_lines="warn"
)

print("Python table:", python_reviews.shape)
print("MySQL table:", mysql_reviews.shape)

C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 428: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 1587: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 3771: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 3784: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 4187: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 4590: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 4594: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 5576: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 6001: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 7533: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 7670: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 7727: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 8052: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 9555: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 10012: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 10030: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 10114: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 11102: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 11294: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 11737: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 12252: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 12801: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 12923: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 13104: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 13417: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 14179: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 14352: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 15185: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 17151: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 17887: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 18838: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 19129: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 19580: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 20099: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 20966: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 21037: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 21204: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 21379: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 21743: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 22321: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 22796: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 25218: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 25265: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 26824: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 26976: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 28211: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 28516: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 28873: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 29846: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 29970: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 30489: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 31125: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 31272: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 31906: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 34509: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 34747: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 34912: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 35106: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 35240: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 37300: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 39618: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 40083: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 40383: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 40503: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 42045: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 42511: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 43406: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 45022: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 45433: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 45555: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 46010: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 46398: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 46688: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 47862: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 48138: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 48421: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 48837: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 48948: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 49557: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 50483: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 50726: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 50742: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 51350: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 51716: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 52557: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 52650: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 52979: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 53651: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 53749: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 56398: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 56573: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 56825: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 56884: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 56956: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 57410: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 57499: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 57868: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 57942: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 58139: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 61480: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 62064: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 62384: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 62678: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 62892: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 63030: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 63139: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 63430: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 63525: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 63639: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 63951: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 64793: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 65101: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 65628: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 67047: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 67762: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 68438: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 68607: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 68976: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 69256: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 69348: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 70473: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 73285: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 74722: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 75847: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 76299: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 76433: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 77321: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 77528: ',' expected after '"'

  mysql_reviews = pd.read_csv(
C:\Users\HP\AppData\Local\Temp\ipykernel_26380\1857251677.py:7: ParserWarning: Skipping line 77817: ',' expected after '"'

  mysql_reviews = pd.read_csv(

Python table: (99224, 7)
MySQL table: (99077, 7)

In [83]:
import pandas as pd

mysql_reviews = pd.read_csv(
    r"C:\ProgramData\MySQL\MySQL Server 8.0\Uploads\reviews_mysql_full.csv"
)

print(mysql_reviews.shape)
print(mysql_reviews.head())

ParserError: Error tokenizing data. C error: Expected 7 fields in line 1586, saw 8

In [84]:
import pandas as pd

mysql_reviews = pd.read_csv(
    r"C:\ProgramData\MySQL\MySQL Server 8.0\Uploads\reviews_mysql_full.csv",
    sep=",",
    quotechar='"',
    encoding="utf-8",
    engine="python",
    on_bad_lines="skip"
)

print(mysql_reviews.shape)
print(mysql_reviews.head())
print(mysql_reviews.columns)

(99117, 7)
   7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb  4  \
0  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33  5
1  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b  5
2  e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b  5
3  f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1  5
4  15197aa66ff4d0650b5434f1b46cda19  b18dcdf73be66366873cd26c5724d1dc  1

   no comment                                       no comment.1  \
0  no comment                                         no comment
1  no comment                                         no comment
2  no comment              recebi bem antes do prazo estipulado.
3  no comment  parabéns lojas lannister adorei comprar pela i...
4  no comment                                         no comment

   2018-01-18 00:00:00  2018-01-18 21:46:00
0  2018-03-10 00:00:00  2018-03-11 03:05:00
1  2018-02-17 00:00:00  2018-02-18 14:36:00
2  2017-04-21 00:00:00  2017-04-21 22:02:00
3  2018-03-01 00:00:00  2018-03-02 10:26:00
4  2018-04-13 00:00:00  2018-04-16 00:39:00
Index(['7bc2406110b926393aa56f80a40eba40', '73fc7af87114b39712e6da79b0a377eb',
       '4', 'no comment', 'no comment.1', '2018-01-18 00:00:00',
       '2018-01-18 21:46:00'],
      dtype='object')

In [85]:
import pandas as pd

columns = [
    "review_id",
    "order_id",
    "review_score",
    "review_comment_title",
    "review_comment_message",
    "review_creation_date",
    "review_answer_timestamp"
]

mysql_reviews = pd.read_csv(
    r"C:\ProgramData\MySQL\MySQL Server 8.0\Uploads\reviews_mysql_full.csv",
    names=columns,
    header=None,
    quotechar='"',
    escapechar='"',
    encoding="utf-8",
    engine="python",
    on_bad_lines="skip"
)

print(mysql_reviews.shape)
print(mysql_reviews.head())
print(mysql_reviews.columns)

ValueError: bad escapechar or quotechar value

In [86]:
import pandas as pd

columns = [
    "review_id",
    "order_id",
    "review_score",
    "review_comment_title",
    "review_comment_message",
    "review_creation_date",
    "review_answer_timestamp"
]

mysql_reviews = pd.read_csv(
    r"C:\ProgramData\MySQL\MySQL Server 8.0\Uploads\reviews_mysql_full.csv",
    names=columns,
    header=None,
    quotechar='"',
    encoding="utf-8",
    engine="python",
    on_bad_lines="skip"
)

print(mysql_reviews.shape)
print(mysql_reviews.head())
print(mysql_reviews.columns)

(99118, 7)
                          review_id                          order_id  \
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b
3  e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b
4  f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1

  review_score review_comment_title  \
0            4           no comment
1            5           no comment
2            5           no comment
3            5           no comment
4            5           no comment

                              review_comment_message review_creation_date  \
0                                         no comment  2018-01-18 00:00:00
1                                         no comment  2018-03-10 00:00:00
2                                         no comment  2018-02-17 00:00:00
3              recebi bem antes do prazo estipulado.  2017-04-21 00:00:00
4  parabéns lojas lannister adorei comprar pela i...  2018-03-01 00:00:00

  review_answer_timestamp
0     2018-01-18 21:46:00
1     2018-03-11 03:05:00
2     2018-02-18 14:36:00
3     2017-04-21 22:02:00
4     2018-03-02 10:26:00
Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='object')

In [87]:
python_reviews = pd.read_csv(
    r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\reviews_clean.csv"
)

print("Python:", python_reviews.shape)
print("MySQL:", mysql_reviews.shape)

Python: (99224, 7)
MySQL: (99118, 7)

In [88]:
difference = python_reviews.merge(
    mysql_reviews[['review_id']],
    on="review_id",
    how="left",
    indicator=True
)

missing_rows = difference[difference["_merge"]=="left_only"]

print(missing_rows.shape)

missing_rows.head()

(174, 8)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,_merge
431,320ae91d4c5cb8164c168fc68392a5fb,934e266bc66e8ed5bba8266dfde60175,1,produto pirata!,"quando instalei o cartucho de tinta, a minha i...",2018-05-22 00:00:00,2018-05-23 01:03:00,left_only
1607,10f9300f8637c13e5691f6354205006d,61af52f7cc6266b9aead2cc464aa48f0,4,no comment,"respondi que sim para ""recebi o produto corret...",2018-06-09 00:00:00,2018-06-10 11:39:00,left_only
3826,9d3838017d22783aa67ba9c557b8c43b,12aba4fdeb04e5cca1132f86f2bda749,5,no comment,"previsto para chegar 27/11, mas já está em min...",2017-11-11 00:00:00,2017-11-11 20:42:00,left_only
3839,91d696370490d901858c8492475a2cde,063f19fae1eadbb92dc30d00b7cc870c,2,produto veio sem peça,produto veio sem peça importante para prender ...,2018-08-17 00:00:00,2018-08-18 00:44:00,left_only
4244,a0359a6c972cb2efd5b1afd3f3ba4903,ac3c62295b2d88214642ed7f7114d468,4,no comment,a única questão foi um comunicado que recebi d...,2018-02-25 00:00:00,2018-02-26 16:02:00,left_only

In [89]:
missing_reviews = python_reviews[
    python_reviews["review_id"].isin(missing_rows["review_id"])
]

missing_reviews

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
426,320ae91d4c5cb8164c168fc68392a5fb,934e266bc66e8ed5bba8266dfde60175,1,produto pirata!,"quando instalei o cartucho de tinta, a minha i...",2018-05-22 00:00:00,2018-05-23 01:03:00
1585,10f9300f8637c13e5691f6354205006d,61af52f7cc6266b9aead2cc464aa48f0,4,no comment,"respondi que sim para ""recebi o produto corret...",2018-06-09 00:00:00,2018-06-10 11:39:00
3769,9d3838017d22783aa67ba9c557b8c43b,12aba4fdeb04e5cca1132f86f2bda749,5,no comment,"previsto para chegar 27/11, mas já está em min...",2017-11-11 00:00:00,2017-11-11 20:42:00
3782,91d696370490d901858c8492475a2cde,063f19fae1eadbb92dc30d00b7cc870c,2,produto veio sem peça,produto veio sem peça importante para prender ...,2018-08-17 00:00:00,2018-08-18 00:44:00
4185,a0359a6c972cb2efd5b1afd3f3ba4903,ac3c62295b2d88214642ed7f7114d468,4,no comment,a única questão foi um comunicado que recebi d...,2018-02-25 00:00:00,2018-02-26 16:02:00
...,...,...,...,...,...,...,...
97077,6d22562cc287fa8c6e1b8ad4e8d74b02,1d8213566e4ed04b2a4659f52a1021b9,4,bom produto,"único problema é que a tinta não ""se prender"" ...",2018-06-15 00:00:00,2018-06-18 11:09:00
97141,28cdfc7cf5c185b2f1583f3aeba62f7d,2ac69ee25b6ceeb2cc1675c34254f0f3,4,no comment,estas empresas que mandam os produtos desmonta...,2017-08-02 00:00:00,2017-08-03 10:51:00
98456,0105ea6487b1325651dc5372adb05152,c9f23db8a1cb725df9bdb3383bd72b38,4,no comment,"só não acho justo pagar ""entrega"" e ter que me...",2017-12-28 00:00:00,2017-12-29 10:49:00
98974,ff1b17c14d325000c4e2e54afd18c2f0,180956bcbdf2ff42e547ec8dec11ed1f,1,no comment,o único produto que chegou nesse pedido foi a ...,2018-01-24 00:00:00,2018-01-29 14:03:00
99041,e1bc9e2f33c3fa1cb40845c285f0c02b,dd359d3c294458c6d642b2eea9212bf5,2,no comment,"já comprei várias vezes no site ""lannister"";ma...",2016-11-27 00:00:00,2016-11-29 14:19:00

In [90]:
missing_reviews["review_id"].head(10)

426     320ae91d4c5cb8164c168fc68392a5fb
1585    10f9300f8637c13e5691f6354205006d
3769    9d3838017d22783aa67ba9c557b8c43b
3782    91d696370490d901858c8492475a2cde
4185    a0359a6c972cb2efd5b1afd3f3ba4903
4588    b7dbdda9b7b45913dc066e6cf2604f26
4591    fcaccf956b3b8b0b7f30b13712ed6037
5573    60a7d138d21e67f0bfaeedee9a7ab783
5998    dcb5a99ac081043da014276823f67c51
7530    f664eed4cac21e21550d573040955d62
Name: review_id, dtype: object

In [91]:
mysql_reviews[
    mysql_reviews["review_id"] == "320ae91d4c5cb8164c168fc68392a5fb"
]

Empty DataFrame
Columns: [review_id, order_id, review_score, review_comment_title, review_comment_message, review_creation_date, review_answer_timestamp]
Index: []

In [92]:
print(mysql_reviews.shape)

(99118, 7)

In [93]:
print(mysql_reviews["review_id"].duplicated().sum())

850

In [96]:
cols = [
    "review_id",
    "order_id",
    "review_score",
    "review_comment_title",
    "review_comment_message",
    "review_creation_date",
    "review_answer_timestamp"
]

python_reviews = python_reviews[cols].astype(str)
mysql_reviews = mysql_reviews[cols].astype(str)

In [97]:
difference = python_reviews.merge(
    mysql_reviews,
    how="outer",
    indicator=True
)

difference["_merge"].value_counts()

_merge
both          96368
left_only      2856
right_only     2750
Name: count, dtype: int64

In [98]:
missing = difference[difference["_merge"] == "left_only"]

print(missing.shape)
missing.head()

(2856, 8)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,_merge
29,00112b1cb3cd58339c91aad88df2b835,c7068b2d09a51ca53dd0a06c2526be34,4,entrega muito rápida,nota 10 pela entrega.\r\no produto não tem a c...,2018-05-03 00:00:00,2018-05-03 22:14:00,left_only
31,00125f12c201cf0160f4a1457b466512,659a4b8e5c9540667f4d4d5607bc8f79,2,no comment,o produto chegou no prazo porém o item veio er...,2018-03-13 00:00:00,2018-03-15 12:20:00,left_only
34,00130cbe1f9d422698c812ed8ded1919,04a28263e085d399c97ae49e0b477efa,1,no comment,"o cartucho ""original hp"" 60xl não é reconhecid...",2018-03-07 00:00:00,2018-03-20 18:08:00,left_only
35,00130cbe1f9d422698c812ed8ded1919,dfcdfc43867d1c1381bfaf62d6b9c195,1,no comment,"o cartucho ""original hp"" 60xl não é reconhecid...",2018-03-07 00:00:00,2018-03-20 18:08:00,left_only
41,00180271bf8a82fca45f1aef1dcb837b,1d61263296787e98a9e59fcaa66265af,5,no comment,muito feliz com minha compra. o pedido chegou ...,2018-05-16 00:00:00,2018-05-16 22:25:00,left_only

In [99]:
missing_cols = missing.columns[:-1]

for col in missing_cols:
    print(
        col,
        missing[col].notna().sum()
    )

review_id 2856
order_id 2856
review_score 2856
review_comment_title 2856
review_comment_message 2856
review_creation_date 2856
review_answer_timestamp 2856

In [100]:
difference_key = python_reviews.merge(
    mysql_reviews,
    on=["review_id","order_id"],
    how="outer",
    indicator=True
)

difference_key["_merge"].value_counts()

_merge
both          99050
left_only       174
right_only       68
Name: count, dtype: int64

In [101]:
python_missing = difference_key[
    difference_key["_merge"] == "left_only"
]

python_missing.head()

,review_id,order_id,review_score_x,review_comment_title_x,review_comment_message_x,review_creation_date_x,review_answer_timestamp_x,review_score_y,review_comment_title_y,review_comment_message_y,review_creation_date_y,review_answer_timestamp_y,_merge
32,00130cbe1f9d422698c812ed8ded1919,04a28263e085d399c97ae49e0b477efa,1,no comment,"o cartucho ""original hp"" 60xl não é reconhecid...",2018-03-07 00:00:00,2018-03-20 18:08:00,NaN,NaN,NaN,NaN,NaN,left_only
33,00130cbe1f9d422698c812ed8ded1919,dfcdfc43867d1c1381bfaf62d6b9c195,1,no comment,"o cartucho ""original hp"" 60xl não é reconhecid...",2018-03-07 00:00:00,2018-03-20 18:08:00,NaN,NaN,NaN,NaN,NaN,left_only
380,00fba0108ba062f435a943e592075e6d,d02a0111cedc20a548cb065955e04968,5,no comment,"o produto de excelente qualidade, o único prob...",2017-12-02 00:00:00,2017-12-03 12:23:00,NaN,NaN,NaN,NaN,NaN,left_only
394,0105ea6487b1325651dc5372adb05152,c9f23db8a1cb725df9bdb3383bd72b38,4,no comment,"só não acho justo pagar ""entrega"" e ter que me...",2017-12-28 00:00:00,2017-12-29 10:49:00,NaN,NaN,NaN,NaN,NaN,left_only
596,01822b206cbbf85560305930977ca8f7,85a00341850d3ac099340d190e2ec046,1,no comment,"no status do meu pedido estava ""dificuldade na...",2018-04-19 00:00:00,2018-04-19 10:51:00,NaN,NaN,NaN,NaN,NaN,left_only

In [102]:
row_python = python_reviews[
    (python_reviews["review_id"]=="00130cbe1f9d422698c812ed8ded1919") &
    (python_reviews["order_id"]=="04a28263e085d399c97ae49e0b477efa")
]

row_mysql = mysql_reviews[
    (mysql_reviews["review_id"]=="00130cbe1f9d422698c812ed8ded1919") &
    (mysql_reviews["order_id"]=="04a28263e085d399c97ae49e0b477efa")
]

print("PYTHON:")
print(repr(row_python["review_comment_message"].iloc[0]))

print("\nMYSQL:")
print(repr(row_mysql["review_comment_message"].iloc[0]))

PYTHON:
'o cartucho "original hp" 60xl não é reconhecido pela impressora, consequentemente não funcionou. além de ter chegado com atraso de mais de 15 dias do previsto. preciso que seja trocado.'

MYSQL:

IndexError: single positional indexer is out-of-bounds

In [103]:
print(len(row_python["review_comment_message"].iloc[0]))
print(len(row_mysql["review_comment_message"].iloc[0]))

185

IndexError: single positional indexer is out-of-bounds

In [104]:
path = r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\reviews_clean.csv"

with open(path, "rb") as f:
    print(f.readline())
    print(f.readline())

b'review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp\r\n'
b'7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,no comment,no comment,2018-01-18 00:00:00,2018-01-18 21:46:00\r\n'

In [105]:
print(python_reviews.shape)

print(
    python_reviews[
        ["review_id", "order_id"]
    ].duplicated().sum()
)

(99224, 7)
0

In [106]:
path = r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\reviews_clean.csv"

with open(path, "r", encoding="utf-8") as f:
    total_lines = sum(1 for _ in f)

print("Total lines:", total_lines)
print("Data rows:", total_lines - 1)

Total lines: 103080
Data rows: 103079

In [107]:
python_reviews.to_csv(
    r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\reviews_clean_NEW.csv",
    index=False
)

In [108]:
path = r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\reviews_clean_NEW.csv"

with open(path, "r", encoding="utf-8") as f:
    print(sum(1 for _ in f) - 1)

103079

In [109]:
print(python_reviews.shape)

(99224, 7)

In [110]:
print("python_reviews:", python_reviews.shape)
print("reviews_clean:", reviews_clean.shape)

python_reviews: (99224, 7)
reviews_clean: (99224, 7)

In [111]:
print(id(python_reviews))
print(id(reviews_clean))

2351659235968
2351558358112

In [112]:
print(python_reviews.equals(reviews_clean))

False

In [113]:
import pandas as pd

test = pd.read_csv(
    r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\reviews_clean_NEW.csv"
)

print(test.shape)

(99224, 7)

In [114]:
mysql_reviews = pd.read_sql(
    "SELECT * FROM reviews",
    con=connection
)

print(mysql_reviews.shape)

NameError: name 'connection' is not defined

In [1]:
print(python_sellers.shape)

NameError: name 'python_sellers' is not defined

In [2]:
import pandas as pd

python_sellers = pd.read_csv(
    r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\sellers_clean.csv"
)

print(python_sellers.shape)
print(python_sellers.head())

(3095, 4)
                          seller_id  seller_zip_code_prefix  \
0  3442f8959a84dea7ee197c632cb2df15                   13023
1  d1b65fc7debc3361ea86b5f14c68d2e2                   13844
2  ce3ad9de960102d0677a81f5d0bb7b2d                   20031
3  c0f3eea2e14555b6faeea3dd58c1b1c3                    4195
4  51a04a8a6bdcb23deccc82b0b80742cf                   12914

         seller_city seller_state
0           campinas           SP
1         mogi guacu           SP
2     rio de janeiro           RJ
3          sao paulo           SP
4  braganca paulista           SP

In [3]:
python_sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [1]:
import pandas as pd

test = pd.read_csv(
    r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\geolocation_clean.csv"
)

print(test.shape)

(1000163, 5)

In [2]:
print(test.head())

   geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                         1037       -23.545621       -46.639292
1                         1046       -23.546081       -46.644820
2                         1046       -23.546129       -46.642951
3                         1041       -23.544392       -46.639499
4                         1035       -23.541578       -46.641607

  geolocation_city geolocation_state
0        sao paulo                SP
1        sao paulo                SP
2        sao paulo                SP
3        sao paulo                SP
4        sao paulo                SP

In [3]:
print("Total rows:", test.shape[0])
print("Unique zip prefixes:", test["geolocation_zip_code_prefix"].nunique())

Total rows: 1000163
Unique zip prefixes: 19015

In [4]:
print("Min ZIP:", test["geolocation_zip_code_prefix"].min())
print("Max ZIP:", test["geolocation_zip_code_prefix"].max())

Min ZIP: 1001
Max ZIP: 99990

In [5]:
path = r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\geolocation_clean.csv"

with open(path, "rb") as f:
    print(f.readline())
    print(f.readline())

b'geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state\r\n'
b'1037,-23.54562128,-46.63929205,sao paulo,SP\r\n'

In [6]:
import pandas as pd

test = pd.read_csv(
    r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\product_category_name_translation_clean.csv"
)

print(test.shape)
print(test.head())

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\HP\\Downloads\\DA PROJECT\\Cleaned Data\\product_category_name_translation_clean.csv'

In [7]:
import pandas as pd

test = pd.read_csv(
    r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\category_translation_clean.csv"
)

print(test.shape)
print(test.head())

(71, 2)
    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [8]:
import pandas as pd
import os

files = {
    "customers": r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\customers_clean.csv",
    "orders": r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\orders_clean.csv",
    "order_items": r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\order_items_clean.csv",
    "payments": r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\payments_clean.csv",
    "reviews": r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\reviews_clean.csv",
    "products": r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\products_clean.csv",
    "sellers": r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\sellers_clean.csv",
    "geolocation": r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\geolocation_clean.csv",
    "category": r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\category_translation_clean.csv"
}

python_results = []

for table, path in files.items():
    df = pd.read_csv(path)
    
    python_results.append({
        "table": table,
        "rows": df.shape[0],
        "columns": df.shape[1]
    })

python_check = pd.DataFrame(python_results)

print(python_check)

         table     rows  columns
0    customers    99441        5
1       orders    99441       12
2  order_items   112650        8
3     payments   103886        5
4      reviews    99224        7
5     products    32951       10
6      sellers     3095        4
7  geolocation  1000163        5
8     category       71        2

In [9]:
print("ORDERS:")
print(pd.read_csv(
    r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\orders_clean.csv"
).columns.tolist())

print("\nORDER ITEMS:")
print(pd.read_csv(
    r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\order_items_clean.csv"
).columns.tolist())

print("\nPRODUCTS:")
print(pd.read_csv(
    r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\products_clean.csv"
).columns.tolist())

ORDERS:
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'delivery_days', 'approval_days', 'delay_days', 'delay_status']

ORDER ITEMS:
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value', 'total_amount']

PRODUCTS:
['product_id', 'product_category_name', 'product_name_length', 'product_description_length', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm', 'product_volume_cm3']

In [10]:
difference = python_reviews.merge(
    mysql_reviews[["review_id", "order_id"]],
    on=["review_id", "order_id"],
    how="left",
    indicator=True
)

missing_reviews = difference[
    difference["_merge"] == "left_only"
]

print(missing_reviews[["review_id", "order_id"]])
print(missing_reviews.shape)

NameError: name 'python_reviews' is not defined

In [11]:
import pandas as pd

reviews_clean = pd.read_csv(
    r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\reviews_clean.csv"
)

reviews_new = pd.read_csv(
    r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\reviews_clean_NEW.csv"
)

print("reviews_clean:", reviews_clean.shape)
print("reviews_new:", reviews_new.shape)

reviews_clean: (99224, 7)
reviews_new: (99224, 7)

In [12]:
print("reviews_clean columns:")
print(reviews_clean.columns.tolist())

print("\nreviews_new columns:")
print(reviews_new.columns.tolist())

reviews_clean columns:
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

reviews_new columns:
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

In [13]:
print(
    "Same shape:",
    reviews_clean.shape == reviews_new.shape
)

print(
    "Same data:",
    reviews_clean.equals(reviews_new)
)

Same shape: True
Same data: True

In [14]:
review_id = "00130cbe1f9d422698c812ed8ded1919"

print("reviews_clean:")
print(
    reviews_clean[
        reviews_clean["review_id"] == review_id
    ]
)

print("\nreviews_new:")
print(
    reviews_new[
        reviews_new["review_id"] == review_id
    ]
)

reviews_clean:
                              review_id                          order_id  \
29841  00130cbe1f9d422698c812ed8ded1919  04a28263e085d399c97ae49e0b477efa
46678  00130cbe1f9d422698c812ed8ded1919  dfcdfc43867d1c1381bfaf62d6b9c195

       review_score review_comment_title  \
29841             1           no comment
46678             1           no comment

                                  review_comment_message review_creation_date  \
29841  o cartucho "original hp" 60xl não é reconhecid...  2018-03-07 00:00:00
46678  o cartucho "original hp" 60xl não é reconhecid...  2018-03-07 00:00:00

      review_answer_timestamp
29841     2018-03-20 18:08:00
46678     2018-03-20 18:08:00

reviews_new:
                              review_id                          order_id  \
29841  00130cbe1f9d422698c812ed8ded1919  04a28263e085d399c97ae49e0b477efa
46678  00130cbe1f9d422698c812ed8ded1919  dfcdfc43867d1c1381bfaf62d6b9c195

       review_score review_comment_title  \
29841             1           no comment
46678             1           no comment

                                  review_comment_message review_creation_date  \
29841  o cartucho "original hp" 60xl não é reconhecid...  2018-03-07 00:00:00
46678  o cartucho "original hp" 60xl não é reconhecid...  2018-03-07 00:00:00

      review_answer_timestamp
29841     2018-03-20 18:08:00
46678     2018-03-20 18:08:00

In [15]:
print(
    "reviews_clean duplicate review_ids:",
    reviews_clean["review_id"].duplicated().sum()
)

print(
    "reviews_new duplicate review_ids:",
    reviews_new["review_id"].duplicated().sum()
)

reviews_clean duplicate review_ids: 814
reviews_new duplicate review_ids: 814

In [16]:
mysql_reviews = pd.read_csv(
    r"C:\ProgramData\MySQL\MySQL Server 8.0\Uploads\reviews_mysql_full.csv"
)

print(mysql_reviews.shape)

ParserError: Error tokenizing data. C error: Expected 7 fields in line 1586, saw 8

In [17]:
import pandas as pd
import mysql.connector

ModuleNotFoundError: No module named 'mysql'

In [18]:
print(conn)

NameError: name 'conn' is not defined

In [19]:
%pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-26.7.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Downloading mysql_connector_python-26.7.0-cp313-cp313-win_amd64.whl (17.7 MB)
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
   - -------------------------------------- 0.5/17.7 MB 5.6 MB/s eta 0:00:04
   ----------- ---------------------------- 5.0/17.7 MB 18.3 MB/s eta 0:00:01
   ----------------------- ---------------- 10.5/17.7 MB 22.1 MB/s eta 0:00:01
   ------------------------------------ --- 16.0/17.7 MB 23.3 MB/s eta 0:00:01
   ---------------------------------------- 17.7/17.7 MB 22.0 MB/s  0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-26.7.0
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
import mysql.connector

In [2]:
reviews_clean = pd.read_csv(
    r"C:\Users\HP\Downloads\DA PROJECT\Cleaned Data\reviews_clean.csv"
)

print(reviews_clean.shape)

(99224, 7)

In [4]:
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Mysql",
    database="olist_project"
)

print(conn.is_connected())

True

In [5]:
mysql_reviews = pd.read_sql(
    "SELECT * FROM reviews",
    conn
)

print(mysql_reviews.shape)

C:\Users\HP\AppData\Local\Temp\ipykernel_11648\1051475610.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  mysql_reviews = pd.read_sql(

(99222, 7)

In [6]:
difference = reviews_clean.merge(
    mysql_reviews,
    on=["review_id", "order_id"],
    how="outer",
    indicator=True
)

print(difference["_merge"].value_counts())

_merge
both          99222
left_only         2
right_only        0
Name: count, dtype: int64

In [7]:
missing_reviews = difference[
    difference["_merge"] == "left_only"
]

print(missing_reviews[
    [
        "review_id",
        "order_id",
        "review_score_x",
        "review_comment_title_x",
        "review_comment_message_x",
        "review_creation_date_x",
        "review_answer_timestamp_x"
    ]
])

                              review_id                          order_id  \
16092  29a50943bdeaba02e4a222241a4b583a  f63f9a7699e3674c80a4ba92e56dfbb8
80378  ceef71ec8c12263b2435a71d581b4716  6a8e811c00442dbe2725f7a4edefd6c9

       review_score_x  review_comment_title_x  \
16092               5              no comment
80378               1  problema com a entrega

                                review_comment_message_x  \
16092      minha primeira compra to satisfeito muito bom
80378  o produto não foi entregue. \r\n\r\nem 19/04 o...

      review_creation_date_x review_answer_timestamp_x
16092    2017-10-11 00:00:00       2017-10-11 15:56:00
80378    2018-05-04 00:00:00       2018-05-04 13:13:00

In [8]:
SELECT *
FROM reviews
WHERE
    (review_id = '29a50943bdeaba02e4a222241a4b583a'
     AND order_id = 'f63f9a7699e3674c80a4ba92e56dfbb8')
OR
    (review_id = 'ceef71ec8c12263b2435a71d581b4716'
     AND order_id = '6a8e811c00442dbe2725f7a4edefd6c9');

SyntaxError: invalid syntax (2434872623.py, line 1)

In [9]:
missing_rows = reviews_clean[
    (
        (reviews_clean["review_id"] == "29a50943bdeaba02e4a222241a4b583a") &
        (reviews_clean["order_id"] == "f63f9a7699e3674c80a4ba92e56dfbb8")
    )
    |
    (
        (reviews_clean["review_id"] == "ceef71ec8c12263b2435a71d581b4716") &
        (reviews_clean["order_id"] == "6a8e811c00442dbe2725f7a4edefd6c9")
    )
]

print(missing_rows.shape)
print(missing_rows.to_string(index=False))

(2, 7)
                       review_id                         order_id  review_score   review_comment_title                                                                                                                                                                   review_comment_message review_creation_date review_answer_timestamp
29a50943bdeaba02e4a222241a4b583a f63f9a7699e3674c80a4ba92e56dfbb8             5             no comment                                                                                                                                            minha primeira compra to satisfeito muito bom  2017-10-11 00:00:00     2017-10-11 15:56:00
ceef71ec8c12263b2435a71d581b4716 6a8e811c00442dbe2725f7a4edefd6c9             1 problema com a entrega o produto não foi entregue. \r\n\r\nem 19/04 os correios informaram que houve um imprevisto na entrega.\r\n\r\nsolicitei o estorno da compra e estou aguardando as devidas providências.  2018-05-04 00:00:00     2018-05-04 13:13:00

In [10]:
cursor = conn.cursor()

insert_sql = """
INSERT INTO reviews (
    review_id,
    order_id,
    review_score,
    review_comment_title,
    review_comment_message,
    review_creation_date,
    review_answer_timestamp
)
VALUES (%s, %s, %s, %s, %s, %s, %s)
"""

for _, row in missing_rows.iterrows():
    cursor.execute(
        insert_sql,
        tuple(row)
    )

conn.commit()

print("2 rows inserted successfully.")

2 rows inserted successfully.

In [11]:
mysql_reviews = pd.read_sql(
    "SELECT * FROM reviews",
    conn
)

print("Python:", reviews_clean.shape)
print("MySQL :", mysql_reviews.shape)

C:\Users\HP\AppData\Local\Temp\ipykernel_11648\2935421322.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  mysql_reviews = pd.read_sql(

Python: (99224, 7)
MySQL : (99224, 7)

In [12]:
difference = reviews_clean.merge(
    mysql_reviews,
    on=["review_id", "order_id"],
    how="outer",
    indicator=True
)

print(difference["_merge"].value_counts())

_merge
both          99224
left_only         0
right_only        0
Name: count, dtype: int64